apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-eks-app
  name: flask-eks-deployment
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: flask-eks-app      
  template:
    metadata:
      labels:
        app: flask-eks-app        
    spec:
      containers:
      - name: flask-eks-app
        image: 851725544255.dkr.ecr.us-east-1.amazonaws.com/flask_eks_docker_image:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"