apiVersion: v1
kind: Service
metadata:
  name: flask-eks-service
spec:
  selector:
    app.kubernetes.io/name: flask-eks-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
